create extension if not exists pgcrypto;

create table users (id uuid primary key default gen_random_uuid(), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table wallets (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id), address varchar not null, chain_id integer not null, verified boolean not null default false, created_at timestamptz not null default now(), unique(address, chain_id));
create table policies (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id), version integer not null, policy_json jsonb not null, policy_hash varchar, status varchar not null, created_at timestamptz not null default now(), unique(user_id, version));
create table portfolio_snapshots (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id), wallet_id uuid not null references wallets(id), total_value_usd numeric not null, portfolio_json jsonb not null, risk_score integer not null check (risk_score between 0 and 100), source varchar not null, data_timestamp timestamptz not null, created_at timestamptz not null default now());
create table opportunities (id uuid primary key default gen_random_uuid(), protocol_id varchar not null, chain_id integer not null, market_type varchar not null check (market_type in ('DEFI','RWA')), asset_address varchar not null, apy numeric not null, risk_score integer not null check (risk_score between 0 and 100), liquidity_score integer not null check (liquidity_score between 0 and 100), executable boolean not null default false, metadata jsonb not null, source varchar not null, data_timestamp timestamptz not null);
create table strategies (id uuid primary key default gen_random_uuid(), user_id uuid not null references users(id), intent_json jsonb not null, strategy_json jsonb not null, expected_apy numeric not null, risk_before integer not null, risk_after integer not null, status varchar not null, created_at timestamptz not null default now());
create table simulations (id uuid primary key default gen_random_uuid(), strategy_id uuid not null references strategies(id), simulation_json jsonb not null, policy_status varchar not null, status varchar not null, provider varchar not null, created_at timestamptz not null default now(), expires_at timestamptz not null);
create table executions (id uuid primary key default gen_random_uuid(), strategy_id uuid not null references strategies(id), simulation_id uuid not null references simulations(id), wallet_id uuid not null references wallets(id), tx_hash varchar, chain_id integer not null, status varchar not null, submitted_at timestamptz, confirmed_at timestamptz);

create index portfolio_snapshots_wallet_time_idx on portfolio_snapshots(wallet_id, data_timestamp desc);
create index opportunities_market_time_idx on opportunities(market_type, data_timestamp desc);
create index executions_wallet_status_idx on executions(wallet_id, status);
